### ISSUE TITLE
Temp dirs not found plotting with b15 dev 47, to the root of a mount point on Windows

### ISSUE THREAD

**Issue by kiwihaitch** [Chia-Network/chiapos#103] opened 2020-10-17 06:07 UTC
On windows with a drive mountpoint at: C:\_\SM01\05 - plotting to this directory path fails with a Temp dir not found. If I create a subdir below it, eg C:\_\SM01\05\PLOT - plot works properly.

Log file attached.

**Comment by hoffmang9** [comment] 2020-10-17 06:14
Additional notes:

1. That path as tempdir works under Beta 15
2. It's pretty clearly failing in C++ and not the python layer.

**Comment by hoffmang9** [comment] 2020-10-17 06:17
Windows Server 2016

**Comment by kiwihaitch** [comment] 2020-10-17 06:18
OS: Server 2016. Log re-attached 

[b15.47-plot-error.txt](https://github.com/Chia-Network/chiapos/files/5395066/b15.47-plot-error.txt)

**Comment by arvidn** [comment] 2020-10-19 12:51
I tried to reproduce this with the C++ plotting tool, on windows. No luck so far, I'm running:

```
Debug\ProofOfSpace.exe create -k 32 -b 4528 -u 128 -s 65536 -t C:\_\SM01\05 -2 C:\_\SM01\05 -d C:\_\SM01\05
```

(and make sure I create the directory `c:\_\SM01\05`)

Looking at the code, this error comes from:

```
if (!fs::exists(tmp_dirname)) {
   throw InvalidValueException("Temp directory " + tmp_dirname + " does not exist");
}
```

Since the error message says:

```
Caught plotting error: Temp directory C:\_\SM01\05 does not exist
```

It really suggests that the directory "C:\_\SM01\05" indeed does not exist. It's possible that there could be other conditions causing `fs::exists()` to return false though.

**Comment by kiwihaitch** [comment] 2020-10-19 13:37
The Path C:\_\SM01\05 has to be an NTFS Mountpoint for it to fail (ie has another drive mounted there rather than have it's own drive letter). If a directory below the mountpoint is used eg: C:\_\SM01\05\Plot then the plotter is fine. It's only in the specific case of attemptting to plot to the root of the mountpoint.

![image](https://user-images.githubusercontent.com/14339794/96458238-4ef8a380-11e6-11eb-9806-b9556e3ff1b6.png)

**Comment by arvidn** [comment] 2020-10-19 14:04
oh, I see. The log said "C:\_\..." so I missed that you're using the per-drive working directory.

**Comment by arvidn** [comment] 2020-10-19 14:47
I have reproduced the issue

**Comment by arvidn** [comment] 2020-10-19 15:41
https://github.com/gulrak/filesystem/issues/75

**Comment by arvidn** [comment] 2020-11-11 14:08
as far as I can tell, this has been resolved

**Comment by hoffmang9** [comment] 2020-11-11 14:22
This was directly fixed and the lingering other Windows issue should be resolved by https://github.com/Chia-Network/chiapos/pull/125

Closing.

**Closed by hoffmang9** 2020-11-11 14:22 UTC
